export const POLICY_VERSIONS = {
    privacy: "1.0", terms: "1.0", cookies: "1.0", refund: "1.0", disclaimer: "1.0",
    contact: "1.0", retention: "1.0", consent: "1.0",
};

export const POLICY_CONTENT = {
    privacy: { title: "Privacy Policy", sections: [["Who we are", "GoStudyInAustralia is operated by OnTrack Education. For privacy questions or requests, email Info@purplepatcheducation.com."], ["Information we collect", "We collect contact details, date of birth, education, English-test, work, sponsorship and financial-readiness information that you enter. We also record policy consent, timestamps and a network address where available for security and audit purposes."], ["Why and how we use it", "We use this information to provide the requested Australia student-visa readiness assessment, prepare a report, respond to enquiries, protect the service, and meet applicable legal obligations. We do not use it for unrelated purposes without a separate lawful basis."], ["Storage and access", "Data is stored in Firebase/Google Cloud services selected by us. Access is limited to authorised counsellors and service providers who need it to operate the service, subject to access controls and contractual safeguards."], ["Sharing", "We do not sell personal data. We may share it with hosting, authentication and communications providers, or when required by law. We will obtain separate permission before sharing a profile with an education provider or other third party for a new purpose."], ["Your choices and rights", "You may ask to access, correct, withdraw consent for, or delete your personal data by emailing us. Withdrawal does not affect processing already carried out lawfully and may prevent us from providing the assessment."], ["Security", "We use encryption in transit, access controls, least-privilege administration, authentication and audit records. No system is completely secure; please do not provide government identity numbers, bank credentials or payment-card details in free-text fields."]]},
    terms: { title: "Terms of Service", sections: [["Service", "This site provides education counselling information and an Australia student-visa readiness estimate. It is not legal, migration-agent, financial, medical or immigration advice."], ["Your responsibilities", "You must provide accurate information, keep any access details confidential and not misuse the service. You are responsible for decisions made using the assessment."], ["No guarantee", "A score or report is an internal guidance estimate only. Visa decisions are made solely by the Australian Department of Home Affairs."], ["Acceptable use and changes", "We may update the service or these terms. Material policy changes require acceptance of the current version before a new assessment is submitted."]]},
    cookies: { title: "Cookie Policy", sections: [["Current use", "The site uses essential browser storage only to keep the most recently generated assessment available during the current browser session. We do not knowingly deploy advertising cookies or third-party analytics in this application."], ["Your controls", "You can clear site data in your browser. If analytics, advertising or non-essential cookies are introduced, we will present a separate opt-in mechanism before they are set."]]},
    refund: { title: "Refund & Cancellation Policy", sections: [["Current service", "The calculator and information services on this site do not take payments. This policy will be updated before any paid service is introduced."], ["Future payments", "Before accepting a payment, we will show the applicable price, cancellation, refund eligibility, timelines and contact method at checkout."]]},
    disclaimer: { title: "Disclaimer", sections: [["General", "Content is general information for prospective Australian students and may change. Verify requirements directly with the Australian Department of Home Affairs and your education provider."], ["Assessment", "The probability calculator is based solely on self-reported data and an internal scoring framework. It is not an approval prediction or guarantee."]]},
    contact: { title: "Contact Us", sections: [["Privacy, consent, correction or deletion requests", "Email Info@purplepatcheducation.com with the subject “Privacy Request”. Include your name, email used on the site and the request type. We may need to verify identity before acting."], ["Business contact", "OnTrack Education / GoStudyInAustralia, UG 10/11/12, Indralok Complex, Kargil Chowk, Piplod, Surat, Gujarat 395007. Phone: +91 95373 69597."]]},
    retention: { title: "Data Retention & Deletion Policy", sections: [["Retention", "Assessment and enquiry records are retained only while needed for the assessment, counselling follow-up, dispute handling, security and legal obligations. Our operational target is 24 months from the last meaningful interaction, unless a longer period is required by law or a documented retention hold applies."], ["Deletion", "On a verified request or at the end of the applicable retention period, we will delete or irreversibly anonymise personal data from active systems and instruct processors to do the same where applicable. Security and consent audit records may be retained for a limited period where necessary to establish compliance or defend legal claims."], ["Review", "Retention settings and deletion outcomes must be reviewed periodically by the service owner."]]},
    consent: { title: "User Consent Policy", sections: [["How consent works", "Before submitting a visa assessment, you are shown the data categories, purpose, policies and contact method. Consent is collected by a clear affirmative checkbox and recorded with the policy versions and timestamp."], ["Withdrawal", "You can withdraw consent as easily as you gave it by emailing Info@purplepatcheducation.com. We will stop consent-based processing within a reasonable time unless another legal requirement permits or requires retention."], ["Versioning", "We record the Privacy Policy and Terms version accepted for each submission. A material update requires acceptance of the current version before a new submission."]]},
};
